version: '3.9'
services:
  jenkins:
    image: dizthewize/jenkins-lts-jdk8
    container_name: jenkins
    ports:
      - 80:8080
      - 443:8443
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
    driver: local
